### ISSUE TITLE
Kitty doesn't require any special configurations for "Special keyboard combinations"

### ISSUE THREAD

**Issue by carbon-steel** [ziontee113/yt-tutorials#1]
Hi, just FYI, you don't need the kitty config in https://github.com/ziontee113/yt-tutorials/tree/nvim_key_combos_in_alacritty_and_kitty. Kitty, supports an adjusted version of the protocol from [fixterms](http://www.leonerd.org.uk/hacks/fixterms/) out of the box. I use kitty without your suggested configurations and can map in neovim a command to <Tab> and a different command to <C-i> (note that if you only map a command to <Tab>, neovim will apply the same mapping to <C-i>).

This is documented here: https://sw.kovidgoyal.net/kitty/keyboard-protocol/

You can test this yourself by starting a clean instance of kitty with:
`$ kitty -c NONE`

I'd recommend deleting your suggested kitty configs from https://github.com/ziontee113/yt-tutorials/tree/nvim_key_combos_in_alacritty_and_kitty as it may confuse some folks. I'm not sure if there is anything that can be done about your [youtube video](https://youtu.be/lHBD6pdJ-Ng) though...

**Comment by ziontee113** [comment]
Sure. It didn't work well back when I was first making the video. Looks like things have changed. I'll make the video private then.

Thank you for the information.
